### ISSUE TITLE
Turn the icon components into buttons

### ISSUE THREAD

**Issue by Brooklyn-Parsons** [PhillipsPlusThree/waterbnb#11]

**Comment by taylaenns8** [comment]
Filter icons categories successfully converted into buttons.
<img width="812" alt="Screen Shot 2023-06-20 at 4 24 46 PM" src="https://github.com/PhillipsPlusThree/waterbnb/assets/126600228/77dd01ea-18ed-4574-9a15-ccfd125d043b">
